use_frameworks!

platform :ios, '10.0'

target 'FlowerCocoa_Example' do

  pod 'FlowerCocoa', :path => '../'
  pod 'SnapKit', '4.2.0'

  target 'FlowerCocoa_Tests' do
    inherit! :search_paths

    
  end
end
